language: node_js
node_js:
- 6
- 5
- 4
before_script:
- npm install codacy-coverage mocha-lcov-reporter
script:
- node_modules/eslint/bin/eslint.js {src,test}
- node_modules/.bin/istanbul cover node_modules/mocha/bin/_mocha --report lcovonly
  -- -R spec
after_script:
- cat coverage/lcov.info | node_modules/.bin/codacy-coverage
before_deploy:
- rm -rf coverage
deploy:
  provider: npm
  email: ikerin@gmail.com
  api_key:
    secure: pnzAVIiNUsex5AkGsuy3zZ7PR+EUFguJsx7pUxlCnj012XZ+95b/Ibjv5FvkcGvdqFTa4gX5PWfJo6gQyBZXJZoTLzNsi20ybaMyx9fnEIqZfEesMUJ8sveNEirY1U8tyiBaWNTY+CGJJgbZv3mEFC74vl+JnTVmQOKJenGDAviU2Yhgv1Ki2qWbuhgLsvJUKvBxQb1g84czSIYADglrZtpa/O9RiT7qEJTlsDbmc5oP+b5eb5PB+kiAX5UH8N5KFhiKOCGpkuU2yTWaaQHtA58ELdrs9Ma+yll5e8HFa5uvKkL+dz5AJ7+hTX4K6j3czN+0Upm6gIyFxGWrzlVRCLGdC/o8AicP+kECeAGcwhPHnURRxB/EX2Py7SW4JEvMxMJSrrtBfTtFaGX86KQJE9/2cUStZVmqU5FHR2l9M5bfi71gH6iAQaCt/iNVvj25nAKowADtw5i3EZNOsLnsKZDcYb4cecg07cPe0KRVa7B5XHGDZ2e9I5R9s8e5/iv6Gz1ot3dIfjgDkXXaos19CCEf/RuWo9VSOdJpO4awWzazPcQg33LTJri7iT1o4aySk9Jr2bdaWHTjmxNcO55Q8uh8lzU0CnNnNb+v+fOZwqMYvSKC/d+NgSc3iv6k+0GIZk3gInlPtsYtPWA/dHKqnCC2YjOTKszp9DSi5CPIWmk=
  on:
    tags: true
    repo: enhancv/express-braintree-webhooks
notifications:
  email: false
  slack:
    secure: nkcZL4/bvc3NTCVJtIm62HNuSV7ElxoV2nXLVjSJjuCdRe+x0SFOoY70sNOCd51QvOLdhglOZeEnTX46fe20KnSSbd9I6GKOr1dR5r6EWrT/1swjSQZKJnalDzhUSd4xV1sehmDc1duqpO1XhMJIzcPyWqj1fIQBuHzCHw7AV586JUsV5mCaZVr/6rQol8Vyw08cQZnhsrgAhXeuZbK07ab97i6fqz8iFmGQgvZiW7KOQElmQK6+C6NvkxHBUfgnUuN5U13siJzoQq+RCf3UX/LDNGHDlgqTnIw1gpK8pcIeQ53527AvHU2iOzO2+TJIYEgTJy+CzfWZpWrxCMWHMqzpeDjZCVJZWh85vPKdx/6itQnDEd4GuTcreOxdUdSJnKDlQ9qLdeRy4Pz7WR4vlseDX9QCaEHm6lukATZRfZUXJePN5fXZhfU+zooiXvr9RPBpmA6YPm39xeFBX7EZyhuEIvTlbUIIw3EA7ng55i5np879sk65/dLaagi/jH5xZ7tqSISe+OAzeQAwI0qFx+4fvWFgGXh8MnfM6HyoeLxdq8V40D5wCBNj/Ji5UeGYNfxm/h38dgmQHDeqMj0MLndrXosRs+pUgKmXWX8ClgiED1EymManoANdE50UYK7MJGso4QxbILkCs3/XTy2hOPG1NHOc6S3Kx/b1JN8PhU0=
